# Generated by Django 5.1.6 on 2025-05-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
