# Generated by Django 5.1.6 on 2025-04-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionnaire',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('Girlfriend', 'Girlfriend'), ('Boyfriend', 'Boyfriend'), ('Friend', 'Friendship'), ('BFF', 'Best friend'), ('College mate', 'Study partner'), ('Serious partner', 'Serious relationship'), ('Hookup', 'Casual connection'), ('FWB', 'Friends with benefits'), ('Chill vibe', 'No expectations'), ('Not sure yet', 'Still figuring it out'), ('Chat', 'Interesting conversations')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='compatibility',
            field=models.CharField(choices=[('Very important', 'Very important'), ('Somewhat important', 'Somewhat important'), ("I'm open to exploring any kind of relationship", "I'm open to exploring any kind of relationship"), ('Not important at all', 'Not important at all')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='dating_approach',
            field=models.CharField(choices=[('I like to take things slow', 'I like to take things slow'), ('I dive in quickly and see where it goes', 'I dive in quickly and see where it goes'), ('I prefer long-term commitment', 'I prefer long-term commitment'), ("I'm just here for fun", "I'm just here for fun")], max_length=100),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='relationship_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Taken', 'Taken'), ("It's complicated", "It's complicated"), ('Not telling', 'Not telling'), ('In an open relationship', 'In an open relationship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='relationship_view',
            field=models.CharField(choices=[('Serious commitment', 'Serious commitment'), ('Fun and casual', 'Fun and casual'), ("I'm unsure", "I'm unsure"), ('Just enjoying the journey', 'Just enjoying the journey')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='similar_interests',
            field=models.CharField(choices=[('Yes, definitely', 'Yes, definitely'), ("I'm open to different interests", "I'm open to different interests"), ('I prefer finding someone with unique interests', 'I prefer finding someone with unique interests')], max_length=100),
        ),
    ]
