# Generated by Django 5.1.6 on 2025-05-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userquestionnaire_looking_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CORE', 'CORE'), ('ECE', 'ECE'), ('Cyber Security', 'Cyber Security'), ('IT', 'IT'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('AI', 'AI'), ('AI DS', 'AI DS')], max_length=50),
        ),
    ]
