# Generated by Django 5.1.6 on 2025-08-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestionnaire',
            old_name='college_events',
            new_name='hobbies_interests',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='college_excitements',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='comm_style',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='compatibility',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='content_posting',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='dating_approach',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='decision_style',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='first_meet',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='free_time',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='friendship_values',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='important_trait',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='introvert_extrovert',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='learning_preferences',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='posting_frequency',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='relationship_view',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='relaxation_methods',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='similar_interests',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='sleep_type',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='weekend_plans',
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='communication_style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='ideal_hangout',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='personality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='looking_for',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='relationship_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
