# Generated by Django 5.1.6 on 2025-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='ideal_hangout',
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('Friendship', 'Friendship'), ('Girlfriend', 'Girlfriend'), ('Boyfriend', 'Boyfriend'), ('Serious Relationship', 'Serious Relationship'), ('FWB', 'FWB'), ('Something Casual', 'Something Casual'), ("Let's see where it goes", "Let's see where it goes")], max_length=50),
        ),
    ]
