# Generated by Django 5.1.6 on 2025-08-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userquestionnaire_ideal_hangout_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileview',
            unique_together={('viewer', 'viewed')},
        ),
    ]
