# Generated by Django 5.1.6 on 2025-08-08 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profileview_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crush',
            options={'verbose_name': 'Crush', 'verbose_name_plural': 'Crushes'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
        migrations.AlterModelOptions(
            name='profileview',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Profile View', 'verbose_name_plural': 'Profile Views'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='has_answered_questionnaire',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_set_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_set_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_profile_locked',
            field=models.BooleanField(default=True, help_text='If true, profile is not publicly visible.'),
        ),
    ]
