# Generated by Django 5.1.6 on 2025-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_crush_options_alter_friendship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_answered_questionnaire',
            field=models.BooleanField(default=False),
        ),
    ]
