# Generated by Django 5.1.6 on 2025-08-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_confessioncomment_confessionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
