# Generated by Django 5.1.6 on 2025-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='confession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Confession', 'verbose_name_plural': 'Confessions'},
        ),
        migrations.AlterModelOptions(
            name='confessioncomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Confession Comment', 'verbose_name_plural': 'Confession Comments'},
        ),
        migrations.AlterModelOptions(
            name='confessionlike',
            options={'ordering': ['-created_at'], 'verbose_name': 'Confession Like', 'verbose_name_plural': 'Confession Likes'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Designates whether the post is visible to everyone.'),
        ),
    ]
